name: dask-pycon
dependencies:
 - dask
 - dask-ml
 - distributed
 - graphviz
 - h5py
 - ipywidgets
 - jupyter
 - jupyterlab
 - matplotlib
 - memory_profiler
 - numba
 - numpy
 - pandas
 - pillow
 - pytables
 - python=3.6
 - s3fs
 - scikit-image
 - scikit-learn
 - scipy
 - pip:
   - gcsfs
   - graphviz
   - cachey
   - snakeviz
